SELECT H.HACKER_ID, H.NAME, SUM(S.MAX_SCORE)
FROM HACKERS AS H
INNER JOIN ( SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS MAX_SCORE
             FROM SUBMISSIONS
             GROUP BY HACKER_ID, CHALLENGE_ID
            ) AS S
USING(HACKER_ID)
GROUP BY H.HACKER_ID, H.NAME
HAVING SUM(S.MAX_SCORE) > 0
ORDER BY 3 DESC, 1 ASC;
